services:
  # Backend API Service
  - type: web
    name: futuresight-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # You'll need to set this in Render dashboard
    healthCheckPath: /
    
  # Frontend Service
  - type: web
    name: futuresight-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
